# Source: https://github.com/PopcornTimeTV/PopcornTimeTV/blob/2db947d4c3aededb70a9f880097ec2736f900147/.github/workflows/ios.yml

name: CI

on: [push]

jobs:
  build:
    name: Build

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        
    - name: Get cache
      uses: actions/cache@v3
      id: cache
      with:
        path: |
          Pods
          PopcornTime.xcworkspace
        key: ${{ runner.os }}-${{ hashFiles('Podfile.lock') }}-v5

    - name: Get dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        gem install bundler
        bundle install
        bundle exec pod repo update
        bundle exec pod install

