# Source: https://github.com/PopcornTimeTV/PopcornTimeTV/blob/2db947d4c3aededb70a9f880097ec2736f900147/.github/workflows/ios.yml

name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_12.5.1.app

    - name: Use cache
      id: cache
      uses: actions/cache@v3
      with:
        path: |
          Pods 
          PopcornTime.xcworkspace
        key: ${{ runner.os }}-${{ hashFiles('Podfile.lock') }}-v2

    - name: get dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        gem install bundler
        bundle install
        bundle exec pod repo update
        bundle exec pod install
        
    - name: Compile
      run: |
        xcodebuild clean archive \
          -workspace PopcornTime.xcworkspace \
          -scheme PopcornTimeiOS \
          -sdk iphoneos \
          -configuration Debug \
          CODE_SIGN_IDENTITY='' \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          ONLY_ACTIVE_ARCH=NO \
          | tee build.log \
          | xcpretty
        
    - name: Generate an unsigned debug ipa
      run: |
        cd ~
        mkdir Payload
        mv ~/Library/Developer/Xcode/Archives/*/*/Products/Applications/*.app ~/Payload/
        zip -r popcorn_time.ipa Payload
        
    - name: Upload ipa
      uses: actions/upload-artifact@v2.2.0
      with:
        name: 'popcorn_time'
        path: ~/popcorn_time.ipa
