# Source: https://github.com/PopcornTimeTV/PopcornTimeTV/blob/2db947d4c3aededb70a9f880097ec2736f900147/.github/workflows/ios.yml

name: CI

on: [push]

jobs:
  build:
    name: Build

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.1'
        bundler-cache: true
        
    - name: Get cache
      uses: actions/cache@v3
      id: cache
      with:
        path: |
          Pods
          PopcornTime.xcworkspace
          Podfile.lock
        key: ${{ runner.os }}_${{ hashFiles('Podfile.lock') }}_v3

    - name: Get dependencies       
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        #cp Podfile.lock test
        #bundle exec pod repo update
        bundle exec pod install
        #diff Podfile.lock test
        
    - name: Compile
      run: |
        sudo xcode-select -s /Applications/Xcode_12.5.1.app
        xcodebuild archive \
          -exportArchive \
          -workspace PopcornTime.xcworkspace \
          -scheme PopcornTimeiOS \
          -sdk iphoneos \
          -configuration Debug \
          CODE_SIGN_IDENTITY='' \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          ONLY_ACTIVE_ARCH=NO
        
    - name: Package
      run: |
        cd ~
        mkdir Payload
        cp -r Library/Developer/Xcode/Archives/*/*/Products/Applications/*.app Payload
        zip -r popcorn_time_ios.ipa Payload
        rm -r Payload
        
    - name: Upload
      uses: actions/upload-artifact@v2.2.0
      with:
        name: 'popcorn_time_ios.zip'
        path: ~/popcorn_time_ios.ipa
